### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by buddyp1952** [FossoresLP/vyatta-wireguard#1]
I just wanted to take this opportunity to thank you for carrying on the work that Lochnair started and to offer willingness help if there is any way that I might be of assistance.

Regards,

Joel

**Comment by FossoresLP** [comment]
Hi, thanks for the offer.
I only have an EdgeRouter Pro 8 with v2 firmware that I do not really use too much so the releases are mostly untested.
In case you have access to EdgeOS devices it would be great if you could check just even basic compatibility (can the kernel module even be loaded).

**Comment by thomas-baumeister** [comment]
Version 1.0.20200330 works well on a ugw4.

Thanks and best regards,
Thomas

**Comment by buddyp1952** [comment]
Hi Thomas,

This is actually very good, because between the two of us we at least
have 2 platforms and EdgeOS versions covered.  I am running 1.10.11 on my
ER-Xs, at least until they get EdgeOS 2.x stable on the MTK platform.  I
duplicated your build environment as best as I could and I am able to build
and test code for the MTK routers using my copy of your environment.  Here
is the modinfo for the last module I built on my environment I running on
my local router:

joel@ubnt:~$ sudo modinfo wireguard
filename:       /lib/modules/3.10.107-UBNT/kernel/net/wireguard.ko
alias:          net-pf-16-proto-16-family-wireguard
alias:          rtnl-link-wireguard
version:        0.0.20200215
author:         Jason A. Donenfeld <Jason@zx2c4.com>
description:    WireGuard secure network tunnel
license:        GPL v2
srcversion:     510BC7BE587DAE635FB0FA0
depends:        ipv6,ip_tunnel
vermagic:       3.10.107-UBNT SMP mod_unload MIPS32_R2 32BIT

I looks exactly like what I got when I was running yours binary.

I haven't built or tested the latest release yet because we are dealing
with this COVID thing just like you are (only not as well as your country)
and I've been ill and had a family member ill as well (neither of us with
COVID thankfully).  If things settle down tonite I will try to load your
latest binary on my local router and see what happens.

By the way, I learned about Circle CI from you.  In my opinion it is way
better than Jenkins or the CI built into Gitlab.  It's really easy to use
and I'm glad I found out about it.  I had to change your .circle-ci file to
get the MTK 1.x software to build but I haven't pushed that change to
github as far as I can remember.

Best Regards,

Joel

**Comment by FossoresLP** [comment]
Hi Joel,

the CI environment is still very much a WIP. I am using GitLab CI for building the Docker images as that's just easier for me and then building the packages on Circle CI with the scripts you already have.
Some of these changes have not been commited yet. Please feel free to open a PR with any improvements on the CI repo.
The CI configs will be moved to this repo later on to have everything in one place. That's what bugged me most about Lochnairs approach and made me set up a totally new CI approach.

At some point I would like to use just a singe CI script and provider but that will take some time.

Best regards,
Pascal

**Comment by buddyp1952** [comment]
I built the latest 20200401 and tested it on my ER-X with no issues

**Comment by User-user00** [comment]
Upgraded ER4 (v2.0.8) from 20200318 to 20200401.  No reboot.  No problems.

**Comment by sysfu** [comment]
dpkg installation failed on an Edgerouter Lite running v2.0.8-hotfix.1

`This package contains the wireguard kernel modules for 3.10.107-UBNT, you're trying to install it on 4.9.79-UBNT. Aborting.`

**Comment by FossoresLP** [comment]
@sysfu Did you use the package for EdgeOS v2.0? There are two different versions and it looks like you tried to install the one for EdgeOS v1.10. Your file should be named wireguard-**v2.0**-e100-1.0.20200401-1.deb if you downloaded the right one.

**Comment by sysfu** [comment]
That was the problem, derp derp. v2.0 package installed without issue, thx.

**Comment by nextstepp** [comment]
Installed on :
Edgerouter X - v2.0 without issue 
Edgerouter Poe 5 v2.0  without issue 
Edgerouter 12P v2.0 without issue 
Edgerouter 4 , 6P v.2 without issue

**Comment by jollyjinx** [comment]
Installed it on USG3p, no problem so far, except for the 'delete interface wireguard' and provisioning failing when one wireguard interface is set to allow routing ( which I opened a ticket here for)

**Comment by phillipmcmahon** [comment]
I don't mind helping to test. I have an Edgerouter SFP and an Edgerouter 6P.

Also, happy to set up a build environment if needed. Just will need some guidance on doing that.

Will you be pushing the latest WG release?

**Comment by FossoresLP** [comment]
Thank you for testing everyone.

I am working on a completely new CI pipeline to ensure quicker releases. This might cause some issues with the package although I hope everything works out well.

Expect a new release in the next few days. This will be marked as a pre-release again even though Wireguard has reached v1.0. Please test it only on non-critical hardware just in case I made a mistake somewhere while recreating Lochnairs build environment.

**Comment by FossoresLP** [comment]
As a first test some preview builds are now released. They have some issues like a wrong version in the package control file.
Please be prepared for issues when testing and use only spare devices. THIS IS NOT A RELEASE BUILD!

**Comment by dc361** [comment]
I tried installing e300 v1 on my Edgerouter 4 but received the following error:

sudo dpkg -i e300-v1.deb
dpkg-deb: error: archive 'e300-v1.deb' contains not understood data member control.tar.xz, giving up
dpkg: error processing e300-v1.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 e300-v1.deb

**Comment by FossoresLP** [comment]
Thanks alot, I totally missed that. I will rebuild with gzip compressed archives. Please note that I will update the existing release.

**Comment by FossoresLP** [comment]
The release has been updated, if you have the time go ahead and test again.

It installs and (for my limited testing) runs fine on my ER-8-Pro now.

**Comment by thomas-baumeister** [comment]
The latest release works fine on my UGW4

**Comment by FossoresLP** [comment]
@thomas-baumeister Just to confirm, are you running 20200401 or 20200426?

**Comment by thomas-baumeister** [comment]
cat /sys/module/wireguard/version
1.0.20200426

**Comment by dc361** [comment]
Latest version (1.0.20200426) installed fine on my ER4 - currently testing and will report any issues.

**Comment by jollyjinx** [comment]
installed the latest version on a usg3 port. works fine so far.

only the deletion via `delete interfaces wireguard` fails as before as soon as one interface is set to `set interfaces wireguard wg0 route-allowed-ips true`

**Comment by rubberneck** [comment]
e100-v1-v1.0.20200426-v1.0.20200319.deb on EdgeRouter Lite v1.10.10 Seems to work just fine.

**Comment by FossoresLP** [comment]
Thanks for testing everyone. In case no issues are found I will release the new build as stable this weekend.

**Comment by User-user00** [comment]
Upgraded ER4 (v2.0.8) from 20200401 to 20200426. No reboot. No problems.
(same as before).   Much appreciated!

**Comment by stoffeastrom** [comment]
Upgraded ERLite-3 v2.0.8.5247496.191120.1124 to 1.0.20200426. No reboot. No problems. Very nice 👍

**Comment by FossoresLP** [comment]
The newest WireGuard version has been released at https://github.com/WireGuard/wireguard-vyatta-ubnt
All future releases will happen in that repository.
Thanks again for the help, I hope you will continue to use this project in it's new home.
