### ISSUE TITLE
Documentation Fix (Repository location)

### ISSUE THREAD

**Issue by User-user00** [FossoresLP/vyatta-wireguard#2]
Didn't know if you were aware that the documentation you provide for install and setup has links for the releases that point back to Lochnair instead of your own repository.
(thanks again for providing the updated packages, very much appreciated)

**Comment by FossoresLP** [comment]
Thanks for the reminder, I will fix that with an overall overhaul of the repository and build system due in the next few weeks. I'll leave this open until then.

**Comment by farmwald** [comment]
Related to this issue is that wireguard install page (https://www.wireguard.com/install/) no longer points to Lochnair. Shouldn't it point to this setup?

**Comment by FossoresLP** [comment]
@farmwald I'll contact the Wireguard team as soon as I have the full build infrastructure setup so I can guarantee continuous releases.

**Comment by FossoresLP** [comment]
This repository has been deprecated and the project is now maintained at https://github.com/WireGuard/wireguard-vyatta-ubnt
Closing this issue as the package will be added back to the install page soon.
